name: Delete old artifacts

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: 0 0 * * 1,3,5

jobs:
  clean_artifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: c-hive/gha-remove-artifacts@v1
      with:
          age: 1 day
          skip-tags: true
