name: Delete old workflows

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: 0 0 * * 1,3,5

jobs:
  clean_artifacts:
    uses: ./.github/workflows/clean_artifacts.yml
    if: ${{ github.event_name == 'workflow_dispatch' }}
  clean_runs:
    runs-on: ubuntu-latest
    needs: [clean_artifacts]
    steps:        
      - uses: Mattraks/delete-workflow-runs@v2
        with:
          keep_minimum_runs: 2
          retain_days: 4
